apiVersion: v2
name: secrets-store-csi-driver
# renovate: datasource=helm depName=secrets-store-csi-driver registryUrl=https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
version: 1.4.7
# renovate: image=registry.k8s.io/csi-secrets-store/driver
appVersion: v1.4.7
kubeVersion: '>=1.25.0-0'
maintainers:
  - name: mohammadsrahman
    email: mohammadsrahman@users.noreply.github.com
dependencies:
  - name: secrets-store-csi-driver
    version: 1.4.7
    repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes cluster.
home: null
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
sources:
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver

