apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.checkoutService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.checkoutService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.checkoutService.name }}
    spec:
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.checkoutService.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        {{- if .Values.seccompProfile.enable }}
        seccompProfile:
          type: {{ .Values.seccompProfile.type }}
        {{- end }}
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
        {{- if .Values.nativeGrpcHealthCheck }}
          image: {{ .Values.images.repository }}/{{ .Values.checkoutService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}-native-grpc-probes
        {{- else }}
          image: {{ .Values.images.repository }}/{{ .Values.checkoutService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
        {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
          {{- if .Values.nativeGrpcHealthCheck }}
            grpc:
              port: {{ .Values.service.port }}
          {{- else }}
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          {{- end }}
          livenessProbe:
          {{- if .Values.nativeGrpcHealthCheck }}
            grpc:
              port: {{ .Values.service.port }}
          {{- else }}
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          {{- end }}
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "{{ .Values.productCatalogService.name }}:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "{{ .Values.shippingService.name }}:50051"
            - name: PAYMENT_SERVICE_ADDR
              value: "{{ .Values.paymentService.name }}:50051"
            - name: EMAIL_SERVICE_ADDR
              value: "{{ .Values.emailService.name }}:5000"
            - name: CURRENCY_SERVICE_ADDR
              value: "{{ .Values.currencyService.name }}:7000"
            - name: CART_SERVICE_ADDR
              value: "{{ .Values.cartService.name }}:7070"
        {{- if .Values.opentelemetryCollector.create }}
            - name: COLLECTOR_SERVICE_ADDR
              value: "{{ .Values.opentelemetryCollector.name }}:4317"
        {{- end }}
        {{- if .Values.googleCloudOperations.tracing }}
            - name: ENABLE_TRACING
              value: "1"
        {{- end }}
        {{- if .Values.googleCloudOperations.profiler }}
            - name: ENABLE_PROFILER
              value: "1"
        {{- end }}
          resources: {{ toYaml .Values.resources | nindent 10 }}
