{{- if .Values.networkPolicies.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  {{- if .Values.frontend.externalService }}
    - {}
  {{- else }}
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.loadGenerator.name }}
    {{- if .Values.frontend.virtualService.create }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.frontend.virtualService.gateway.namespace }}
          podSelector:
            matchLabels:
          {{ .Values.frontend.virtualService.gateway.labelKey }}: {{ .Values.frontend.virtualService.gateway.labelValue }}
    {{- end }}
      ports:
        - port: {{ .Values.containerPort }}
          protocol: TCP
  {{- end }}
  egress:
    - {}
{{- end }}
