{{- if and (not .Values.ingress.enabled ) .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "common.names.name" . }}
    gateway: {{ include "common.names.name" . }}
    {{- if .Values.istio.gateway.labels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.istio.gateway.labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- if .Values.istio.gateway.labels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.istio.gateway.labels "context" $) | nindent 4 }}
    {{- end }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- $baseUrl := include "baseUrl" . }}
        {{- if $baseUrl }}
        - {{ $baseUrl }}
        {{- end }}
        {{- if .Values.istio.virtualService.hosts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.istio.virtualService.hosts "context" $) | nindent 4 }}
        {{- end }}
        {{- range $k, $v := .Values.istio.extraVirtualServices }}
        {{- include "common.tplvalues.render" (dict "value" $v.hosts "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
