{{- if .Values.cartDatabase.externalRedisTlsOrigination.enable }}
apiVersion: v1
data:
  {{ .Values.cartDatabase.externalRedisTlsOrigination.name }}.pem: {{ .Values.cartDatabase.externalRedisTlsOrigination.certificate | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.cartDatabase.externalRedisTlsOrigination.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
