apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.productCatalogService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.productCatalogService.name }}
  ports:
    - name: grpc
      port: 3550
      targetPort: 3550
