apiVersion: v2
# renovate: datasource=helm depName=cert-manager registryUrl=https://charts.jetstack.io
version: v1.17.0
# renovate: image=quay.io/jetstack/cert-manager-controller
appVersion: v1.17.0
description: A Helm chart for cert-manager
home: https://cert-manager.io
icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
kubeVersion: '>=1.25.0-0'
maintainers:
  - email: cert-manager-maintainers@googlegroups.com
    name: cert-manager-maintainers
    url: https://cert-manager.io
  - name: mohammadsrahman
    email: mohammadsrahman@me.com
name: cert-manager
sources:
  - https://github.com/cert-manager/cert-manager
dependencies:
  - name: cert-manager
    version: v1.17.0
    repository: https://charts.jetstack.io