apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.adService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adService.name }}
    spec:
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.adService.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        {{- if .Values.seccompProfile.enable }}
        seccompProfile:
          type: {{ .Values.seccompProfile.type }}
        {{- end }}
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
        {{- if .Values.nativeGrpcHealthCheck }}
          image: {{ .Values.images.repository }}/{{ .Values.adService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}-native-grpc-probes
        {{- else }}
          image: {{ .Values.images.repository }}/{{ .Values.adService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
        {{- end }}
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
          {{- if .Values.nativeGrpcHealthCheck }}
            grpc:
              port: 9555
          {{- else }}
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          {{- end }}
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
          {{- if .Values.nativeGrpcHealthCheck }}
            grpc:
              port: 9555
          {{- else }}
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          {{- end }}
