apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.adService.name }}
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
