{{- if .Values.networkPolicies.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.opentelemetryCollector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.opentelemetryCollector.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.adService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.cartService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.checkoutService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.currencyService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.emailService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.frontend.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.loadGenerator.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.paymentService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.productCatalogService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.recommendationService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.shippingService.name }}
      ports:
        - port: 4317
          protocol: TCP
  egress:
    - {}
{{- end }}
