{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.secretProviderClass.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.secretProviderClass.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    {{- range $key, $value := .Values.secretProviderClass.parameters }}
    {{ $key }}: {{ $value }}
    {{- end }}
  secretObjects:
    {{- range $key, $value := .Values.secretProviderClass.secretObjects }}
    - secretName: {{ $value.secretName }}
      type: {{ $value.type }}
      data:
        {{- range $key, $value := $value.data }}
        {{ $key }}: {{ $value }}
        {{- end }}
    {{- end }}
{{- end }}